[package]
name = "initception"
version = "0.1.0"
authors = ["Sojan James <Sojan.James@gmail.com>"]
edition = "2018"

[dependencies]
nix = "0.14.1"
ipc-channel = "0.12.0"
serde = { version = "1.0", features = ["derive"] }
caps = "0.3.1"


